sudo: required
dist: trusty
language: cpp

before_install:
# Modified Adafruit script for Arduino CI
  - source <(curl -SLs https://raw.githubusercontent.com/blinkinlabs/travis-ci-arduino/master/install.sh)

install:
#  - sudo apt-get -y install qt57[QTPACKAGE] qt57serialport libusb-1.0-0-dev
  - sudo apt-get -y --force-yes install gcc-arm-none-eabi dfu-util
#  - sudo apt-get -y install eagle

script:
# Build Arduino examples
  - build_platform blinkytape
