dist: trusty
language: cpp

before_install:
# Modified Adafruit script for Arduino CI
  - source <(curl -SLs https://raw.githubusercontent.com/blinkinlabs/travis-ci-arduino/master/install.sh)

install:
  - arduino --install-library "FastLED"

script:
# Build Arduino examples
  - build_platform blinkytape
